# This is a basic workflow to help you get started with Actions

name: wrt firmware CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the barrier_breaker branch
  push:
    branches: [ barrier_breaker ]
  pull_request:
    branches: [ barrier_breaker ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install build-essential git subversion wget flex gettext \
          libncurses5-dev unzip gawk liblzma-dev zlib1g-dev ccache u-boot-tools

      # Runs a single command using the runners shell
      - name: buil 
        run: make
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: Padavan-packages
         path: /opt/images
